<html>

<head>
    <link href="index.css" rel="stylesheet" type="text/css">
    <link href="fontawesome-free-6.4.0-web/css/fontawesome.css" rel="stylesheet">
    <link href="fontawesome-free-6.4.0-web/css/brands.css" rel="stylesheet">
    <link href="fontawesome-free-6.4.0-web/css/solid.css" rel="stylesheet">
</head>

<div class='footer_t'>
    <div>
        <i class="fa-solid fa-users-gear" style="color: #ffffff;"></i>
        تهیه کننده: امیر ساجدی فر
    </div>

    <div>
        <i class="fa-sharp fa-solid fa-chalkboard-user" style="color: #fcfcfc;"></i>
        استاد درس: دکتر رجبی
    </div>

</div>

</html>
