<html>

<head>
    <link href="index.css" rel="stylesheet" type="text/css">
    <link href="fontawesome-free-6.4.0-web/css/fontawesome.css" rel="stylesheet">
    <link href="fontawesome-free-6.4.0-web/css/brands.css" rel="stylesheet">
    <link href="fontawesome-free-6.4.0-web/css/solid.css" rel="stylesheet">
</head>

<div class='main_menu'>
    <p>جبر خطی</p>
<ul>
    <a href="index.php">
        <li style="float: right; width: 50px">
            <i class="fa-solid fa-house"></i>
        </li>
    </a>
    <a href="loging.php">
        <li>
            ورود
            <i class="fa-solid fa-arrow-right-to-bracket fa-lg" style="color: #000000;margin-right: 3px"></i>
        </li>
    </a>
    <a href="signing.php">
        <li>ثبت نام</li>
    </a>
</ul>
</div>




</html>